on:
  push:
    branches: main

name: check

jobs:
  check:
    name: Rust build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest stable
        uses: ThexXTURBOXx/toolchain@master
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
          
      - name: Run Clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'

      - name: Run cargo build
        uses: gaoDean/cargo@master
        with:
          command: build
          args: --profile=${{ matrix.profile }}
      
      - name: Upload artifacts
        if: ${{ matrix.profile == 'release' }}
        uses: actions/upload-artifact@v3
        with:
          name: binaryname-linux
          path: target/release/actions