on: [pull_request]

name: check

jobs:
  check:
    name: Rust check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest stable
        uses: ThexXTURBOXx/toolchain@master
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cargo check
        uses: gaoDean/cargo@master
        with:
          command: check
          args: --profile=${{ matrix.profile }}
          
      - name: Run Clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'